# .readthedocs.yaml

version: 2

# Build documentation in the 'docs' directory using Sphinx
sphinx:
  configuration: docs/conf.py

# Set the Python version for the virtual environment
python:
  version: 3.8
  install:
    - requirements: requirements.txt

# If you don't have a requirements.txt, you can specify the dependencies directly
# install:
#   - method: pip
#     path: .

include:
  - "PyPMT.py"
  - ".readthedocs.yaml
