version: 2

# Build documentation using Sphinx
sphinx:
  configuration: docs/conf.py

# Set the Python version for the virtual environment
python:
  version: 3.8
  install:
    - method: pip
      path: .

# If you need to specify the build environment, add this section
build:
  os: ubuntu-22.04

# Include only specific files in the build process
include:
  - "PyPMT.py"  # Replace with the relative path to your .py file
  - ".readthedocs.yaml"

# Exclude unnecessary files from the build
exclude:
  - "*.ipynb"          # Exclude Jupyter notebooks
  - "*.html"           # Exclude HTML files
  - "*.xlsx" # Exclude xlsx files
  - "*.md" # Exclude .md files
